name: Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # ou a versão que você está usando
      - name: Install dependencies
        run: dotnet restore
      - name: Run Reviewdog
        run: |
          dotnet build > build.log
          reviewdog -f=msbuild -reporter=github-pr-review < build.log