name: Reviewdog

on:
  pull_request:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  # use a versão Go que você precisa

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint with Reviewdog
        run: |
          golangci-lint run --out-format=reviewdog | reviewdog -f=golangci-lint -name=golangci-lint -reporter=github-pr-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso ao GitHub
